package Business;

/**
 * CoffeGenerationListener is used to observe coffee generation events in the game.
 * Implementing classes receive notifications when new coffees are generated by active generators.
 */
public interface CoffeGenerationListener {

    /**
     * Called when a new batch of coffees has been generated.
     * @param numCoffees the number of coffees generated
     */
    void newCoffeesGenerated(double numCoffees);
}
